### ISSUE TITLE
Set up GitHub pages

### ISSUE THREAD

**Issue by Sporiff** [OpenPodcastAPI/api-specs#18]
To host the new documentation site, we need to configure a Sphinx build process and set up deployment to GitHub pages. Once this is configured, we can use a custom domain to access the site.

**Comment by keunes** [comment]
I have hooked up the domain with the GH, ready for use with pages. Just wondering if we should have a dedicated/additional repo exclusively for the pages?

**Comment by Sporiff** [comment]
@keunes I think you can just do it with a branch called `gh-pages` in the same repository.

**Comment by keunes** [comment]
Yes, I meant to say branch actually. But so yes, needs to be separate. Thank you!

**Comment by georgkrause** [comment]
You can pick any branch.

If I should work on this, I need to have access to the settings, @keunes

**Comment by georgkrause** [comment]
https://openpodcastapi.github.io/api-specs/

**Comment by keunes** [comment]
I had only added a TXT record to verify the domain, otherwise not. That's now corrected.
