### ISSUE TITLE
RFC2119 capitalisation

### ISSUE THREAD

**Issue by keunes** [OpenPodcastAPI/api-specs#44]
The capitalisation comes from [RFC2119](https://www.rfc-editor.org/rfc/rfc2119), which defined some keywords practical for specification designing. E.g. SHOULD is defined as:
> This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

So the capitalisation indicates that this definition is used.

If we decide to use this, we have to put the following text somewhere prominent in the spec:

```
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
[RFC 2119](https://www.rfc-editor.org/rfc/rfc2119).
```

_Originally posted by @JonOfUs in https://github.com/OpenPodcastAPI/api-specs/pull/42#discussion_r1221328576_

**Comment by Sporiff** [comment]
Fixed in e1b0ef1
