### ISSUE TITLE
Starlight migration: create new sidebar component

### ISSUE THREAD

**Issue by Sporiff** [OpenPodcastAPI/api-specs#64]
We need to add a sidebar footer linking out to Netlify and to our Code of Conduct in order to get the free Netlify hosting.

We can override the sidebar using the built-in [Overrides function](https://starlight.astro.build/reference/overrides/#page-sidebar). We can largely copy the [existing sidebar](https://github.com/withastro/starlight/blob/main/packages/starlight/components/PageSidebar.astro) and build on it.

**Comment by keunes** [comment]
Link to add: "This site is powered by Netlify" pointing to https://www.netlify.com

**Comment by Sporiff** [comment]
This is no longer required.
